return {
  -- Noctalia colorscheme integration
  -- The colorscheme file is auto-generated by Noctalia's Matugen templates
  name = "noctalia",
  dir = vim.fn.stdpath("config") .. "/colors",
  lazy = false,
  priority = 1000,
  config = function()
    -- Load the colorscheme
    local colorscheme_file = vim.fn.stdpath("config") .. "/colors/noctalia.lua"

    -- Check if the colorscheme file exists
    if vim.fn.filereadable(colorscheme_file) == 1 then
      vim.cmd("colorscheme noctalia")

      -- Set up auto-reload when the colorscheme file changes
      vim.api.nvim_create_autocmd({"BufWritePost", "FileChangedShellPost"}, {
        pattern = colorscheme_file,
        callback = function()
          -- Clear the cache for the colorscheme
          package.loaded["noctalia"] = nil

          -- Reload the colorscheme
          vim.cmd("colorscheme noctalia")

          -- Notify the user
          vim.notify("Noctalia colorscheme reloaded", vim.log.levels.INFO)
        end,
        desc = "Auto-reload Noctalia colorscheme when it changes",
      })
    else
      vim.notify(
        "Noctalia colorscheme file not found. Please generate it using Noctalia settings.",
        vim.log.levels.WARN
      )
    end
  end,
}
