-- Noctalia colorscheme for Neovim
-- Auto-generated by Matugen

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.g.colors_name = "noctalia"

-- Color palette
local colors = {
  -- Primary colors
  primary = "#cba6f7",
  on_primary = "#11111b",
  primary_container = "#6b02e9",
  on_primary_container = "#e4d0fb",

  -- Secondary colors
  secondary = "#fab387",
  on_secondary = "#11111b",
  secondary_container = "#ce4f00",
  on_secondary_container = "#100701",

  -- Tertiary colors
  tertiary = "#94e2d5",
  on_tertiary = "#11111b",
  tertiary_container = "#1ba891",
  on_tertiary_container = "#0e352e",

  -- Surface colors
  surface = "#1e1e2e",
  surface_dim = "#161622",
  surface_container_lowest = "#212232",
  surface_container_low = "#272839",
  surface_container = "#313244",
  surface_container_high = "#3a3b50",
  surface_container_highest = "#42435c",
  on_surface = "#cdd6f4",
  on_surface_variant = "#a3b4eb",

  -- Error colors
  error = "#f38ba8",
  on_error = "#11111b",
  error_container = "#c8043a",
  on_error_container = "#fbd7e1",

  -- Outline
  outline = "#646789",
  outline_variant = "#44465d",

  -- Background
  background = "#1e1e2e",
  on_background = "#cdd6f4",
}

-- Helper function to set highlights
local function hi(group, opts)
  local cmd = "highlight " .. group
  if opts.fg then cmd = cmd .. " guifg=" .. opts.fg end
  if opts.bg then cmd = cmd .. " guibg=" .. opts.bg end
  if opts.sp then cmd = cmd .. " guisp=" .. opts.sp end
  if opts.style then cmd = cmd .. " gui=" .. opts.style end
  if opts.link then cmd = "highlight! link " .. group .. " " .. opts.link end
  vim.cmd(cmd)
end

-- Editor
hi("Normal", { fg = colors.on_surface, bg = colors.surface })
hi("NormalFloat", { fg = colors.on_surface, bg = colors.surface_container })
hi("FloatBorder", { fg = colors.outline, bg = colors.surface_container })
hi("Cursor", { fg = colors.surface, bg = colors.on_surface })
hi("CursorLine", { bg = colors.surface_container_high })
hi("CursorLineNr", { fg = colors.primary, style = "bold" })
hi("LineNr", { fg = colors.on_surface_variant })
hi("SignColumn", { bg = colors.surface })
hi("ColorColumn", { bg = colors.surface_container })
hi("Visual", { bg = colors.surface_container_highest })
hi("VisualNOS", { link = "Visual" })
hi("Search", { fg = colors.on_primary_container, bg = colors.primary_container })
hi("IncSearch", { fg = colors.on_tertiary, bg = colors.tertiary })
hi("MatchParen", { fg = colors.primary, style = "bold,underline" })
hi("Folded", { fg = colors.on_surface_variant, bg = colors.surface_container_low })
hi("FoldColumn", { fg = colors.on_surface_variant, bg = colors.surface })
hi("Pmenu", { fg = colors.on_surface, bg = colors.surface_container })
hi("PmenuSel", { fg = colors.on_secondary_container, bg = colors.secondary_container })
hi("PmenuSbar", { bg = colors.surface_container_high })
hi("PmenuThumb", { bg = colors.outline })
hi("StatusLine", { fg = colors.on_surface, bg = colors.surface_container })
hi("StatusLineNC", { fg = colors.on_surface_variant, bg = colors.surface_container_low })
hi("TabLine", { fg = colors.on_surface_variant, bg = colors.surface_container })
hi("TabLineFill", { bg = colors.surface })
hi("TabLineSel", { fg = colors.on_primary_container, bg = colors.primary_container })
hi("VertSplit", { fg = colors.outline_variant })
hi("WinSeparator", { fg = colors.outline_variant })

-- Syntax
hi("Comment", { fg = colors.on_surface_variant, style = "italic" })
hi("Constant", { fg = colors.tertiary })
hi("String", { fg = colors.secondary })
hi("Character", { fg = colors.secondary })
hi("Number", { fg = colors.tertiary })
hi("Boolean", { fg = colors.tertiary })
hi("Float", { fg = colors.tertiary })
hi("Identifier", { fg = colors.on_surface })
hi("Function", { fg = colors.primary })
hi("Statement", { fg = colors.primary })
hi("Conditional", { fg = colors.primary })
hi("Repeat", { fg = colors.primary })
hi("Label", { fg = colors.primary })
hi("Operator", { fg = colors.on_surface_variant })
hi("Keyword", { fg = colors.primary })
hi("Exception", { fg = colors.error })
hi("PreProc", { fg = colors.tertiary })
hi("Include", { fg = colors.primary })
hi("Define", { fg = colors.primary })
hi("Macro", { fg = colors.tertiary })
hi("PreCondit", { fg = colors.primary })
hi("Type", { fg = colors.secondary })
hi("StorageClass", { fg = colors.primary })
hi("Structure", { fg = colors.secondary })
hi("Typedef", { fg = colors.secondary })
hi("Special", { fg = colors.tertiary })
hi("SpecialChar", { fg = colors.secondary })
hi("Tag", { fg = colors.primary })
hi("Delimiter", { fg = colors.on_surface_variant })
hi("SpecialComment", { fg = colors.on_surface_variant, style = "italic" })
hi("Debug", { fg = colors.error })
hi("Underlined", { style = "underline" })
hi("Ignore", { fg = colors.outline_variant })
hi("Error", { fg = colors.error, style = "bold" })
hi("Todo", { fg = colors.tertiary, style = "bold,italic" })

-- Diff
hi("DiffAdd", { fg = colors.on_tertiary_container, bg = colors.tertiary_container })
hi("DiffChange", { fg = colors.on_primary_container, bg = colors.primary_container })
hi("DiffDelete", { fg = colors.on_error_container, bg = colors.error_container })
hi("DiffText", { fg = colors.on_primary, bg = colors.primary })

-- Git signs
hi("GitSignsAdd", { fg = colors.tertiary })
hi("GitSignsChange", { fg = colors.primary })
hi("GitSignsDelete", { fg = colors.error })

-- LSP
hi("DiagnosticError", { fg = colors.error })
hi("DiagnosticWarn", { fg = colors.tertiary })
hi("DiagnosticInfo", { fg = colors.primary })
hi("DiagnosticHint", { fg = colors.secondary })
hi("DiagnosticUnderlineError", { sp = colors.error, style = "underline" })
hi("DiagnosticUnderlineWarn", { sp = colors.tertiary, style = "underline" })
hi("DiagnosticUnderlineInfo", { sp = colors.primary, style = "underline" })
hi("DiagnosticUnderlineHint", { sp = colors.secondary, style = "underline" })
hi("LspReferenceText", { bg = colors.surface_container_high })
hi("LspReferenceRead", { bg = colors.surface_container_high })
hi("LspReferenceWrite", { bg = colors.surface_container_high })

-- Treesitter
hi("@variable", { fg = colors.on_surface })
hi("@variable.builtin", { fg = colors.tertiary })
hi("@variable.parameter", { fg = colors.on_surface })
hi("@variable.member", { fg = colors.on_surface })
hi("@constant", { fg = colors.tertiary })
hi("@constant.builtin", { fg = colors.tertiary })
hi("@constant.macro", { fg = colors.tertiary })
hi("@string", { fg = colors.secondary })
hi("@string.escape", { fg = colors.tertiary })
hi("@string.special", { fg = colors.secondary })
hi("@character", { fg = colors.secondary })
hi("@number", { fg = colors.tertiary })
hi("@boolean", { fg = colors.tertiary })
hi("@float", { fg = colors.tertiary })
hi("@function", { fg = colors.primary })
hi("@function.builtin", { fg = colors.primary })
hi("@function.macro", { fg = colors.tertiary })
hi("@function.call", { fg = colors.primary })
hi("@method", { fg = colors.primary })
hi("@method.call", { fg = colors.primary })
hi("@constructor", { fg = colors.secondary })
hi("@parameter", { fg = colors.on_surface })
hi("@keyword", { fg = colors.primary })
hi("@keyword.function", { fg = colors.primary })
hi("@keyword.operator", { fg = colors.primary })
hi("@keyword.return", { fg = colors.primary })
hi("@conditional", { fg = colors.primary })
hi("@repeat", { fg = colors.primary })
hi("@label", { fg = colors.primary })
hi("@operator", { fg = colors.on_surface_variant })
hi("@exception", { fg = colors.error })
hi("@type", { fg = colors.secondary })
hi("@type.builtin", { fg = colors.secondary })
hi("@type.qualifier", { fg = colors.primary })
hi("@structure", { fg = colors.secondary })
hi("@include", { fg = colors.primary })
hi("@property", { fg = colors.on_surface })
hi("@attribute", { fg = colors.tertiary })
hi("@field", { fg = colors.on_surface })
hi("@namespace", { fg = colors.secondary })
hi("@symbol", { fg = colors.tertiary })
hi("@text", { fg = colors.on_surface })
hi("@text.strong", { style = "bold" })
hi("@text.emphasis", { style = "italic" })
hi("@text.underline", { style = "underline" })
hi("@text.strike", { style = "strikethrough" })
hi("@text.title", { fg = colors.primary, style = "bold" })
hi("@text.literal", { fg = colors.secondary })
hi("@text.uri", { fg = colors.primary, style = "underline" })
hi("@tag", { fg = colors.primary })
hi("@tag.attribute", { fg = colors.tertiary })
hi("@tag.delimiter", { fg = colors.on_surface_variant })
hi("@comment", { fg = colors.on_surface_variant, style = "italic" })
hi("@punctuation.delimiter", { fg = colors.on_surface_variant })
hi("@punctuation.bracket", { fg = colors.on_surface_variant })
hi("@punctuation.special", { fg = colors.tertiary })

-- Telescope
hi("TelescopeBorder", { fg = colors.outline, bg = colors.surface_container })
hi("TelescopeNormal", { fg = colors.on_surface, bg = colors.surface_container })
hi("TelescopeSelection", { fg = colors.on_secondary_container, bg = colors.secondary_container })
hi("TelescopeSelectionCaret", { fg = colors.primary })
hi("TelescopeMatching", { fg = colors.primary, style = "bold" })

-- Neo-tree
hi("NeoTreeNormal", { fg = colors.on_surface, bg = colors.surface_container_low })
hi("NeoTreeNormalNC", { fg = colors.on_surface, bg = colors.surface_container_low })
hi("NeoTreeDirectoryIcon", { fg = colors.primary })
hi("NeoTreeDirectoryName", { fg = colors.on_surface })
hi("NeoTreeFileName", { fg = colors.on_surface })
hi("NeoTreeFileIcon", { fg = colors.on_surface_variant })
hi("NeoTreeGitAdded", { fg = colors.tertiary })
hi("NeoTreeGitModified", { fg = colors.primary })
hi("NeoTreeGitDeleted", { fg = colors.error })

-- Which-key
hi("WhichKey", { fg = colors.primary })
hi("WhichKeyGroup", { fg = colors.secondary })
hi("WhichKeyDesc", { fg = colors.on_surface })
hi("WhichKeySeparator", { fg = colors.on_surface_variant })
hi("WhichKeyFloat", { bg = colors.surface_container })
hi("WhichKeyBorder", { fg = colors.outline })

-- Dashboard (Alpha)
hi("AlphaHeader", { fg = colors.primary })
hi("AlphaButtons", { fg = colors.on_surface })
hi("AlphaShortcut", { fg = colors.secondary })
hi("AlphaFooter", { fg = colors.on_surface_variant, style = "italic" })

-- Notify
hi("NotifyERRORBorder", { fg = colors.error })
hi("NotifyWARNBorder", { fg = colors.tertiary })
hi("NotifyINFOBorder", { fg = colors.primary })
hi("NotifyDEBUGBorder", { fg = colors.on_surface_variant })
hi("NotifyTRACEBorder", { fg = colors.secondary })
hi("NotifyERRORIcon", { fg = colors.error })
hi("NotifyWARNIcon", { fg = colors.tertiary })
hi("NotifyINFOIcon", { fg = colors.primary })
hi("NotifyDEBUGIcon", { fg = colors.on_surface_variant })
hi("NotifyTRACEIcon", { fg = colors.secondary })
hi("NotifyERRORTitle", { fg = colors.error })
hi("NotifyWARNTitle", { fg = colors.tertiary })
hi("NotifyINFOTitle", { fg = colors.primary })
hi("NotifyDEBUGTitle", { fg = colors.on_surface_variant })
hi("NotifyTRACETitle", { fg = colors.secondary })

-- Bufferline
hi("BufferLineBackground", { fg = colors.on_surface_variant, bg = colors.surface_container_low })
hi("BufferLineFill", { bg = colors.surface })
hi("BufferLineBuffer", { fg = colors.on_surface_variant, bg = colors.surface_container_low })
hi("BufferLineBufferSelected", { fg = colors.on_primary_container, bg = colors.primary_container, style = "bold" })
hi("BufferLineBufferVisible", { fg = colors.on_surface, bg = colors.surface_container })
hi("BufferLineTab", { fg = colors.on_surface_variant, bg = colors.surface_container_low })
hi("BufferLineTabSelected", { fg = colors.on_primary_container, bg = colors.primary_container })
hi("BufferLineIndicatorSelected", { fg = colors.primary, bg = colors.primary_container })
hi("BufferLineModified", { fg = colors.tertiary, bg = colors.surface_container_low })
hi("BufferLineModifiedSelected", { fg = colors.tertiary, bg = colors.primary_container })

-- Lualine (uses colorscheme highlights by default, but we can set some specific ones)
hi("lualine_a_normal", { fg = colors.on_primary, bg = colors.primary, style = "bold" })
hi("lualine_a_insert", { fg = colors.on_secondary, bg = colors.secondary, style = "bold" })
hi("lualine_a_visual", { fg = colors.on_tertiary, bg = colors.tertiary, style = "bold" })
hi("lualine_a_replace", { fg = colors.on_error, bg = colors.error, style = "bold" })
hi("lualine_a_command", { fg = colors.on_primary, bg = colors.primary, style = "bold" })

-- CMP (completion)
hi("CmpItemAbbrDeprecated", { fg = colors.outline_variant, style = "strikethrough" })
hi("CmpItemAbbrMatch", { fg = colors.primary, style = "bold" })
hi("CmpItemAbbrMatchFuzzy", { fg = colors.primary })
hi("CmpItemKindVariable", { fg = colors.on_surface })
hi("CmpItemKindInterface", { fg = colors.secondary })
hi("CmpItemKindText", { fg = colors.on_surface })
hi("CmpItemKindFunction", { fg = colors.primary })
hi("CmpItemKindMethod", { fg = colors.primary })
hi("CmpItemKindKeyword", { fg = colors.primary })
hi("CmpItemKindProperty", { fg = colors.on_surface })
hi("CmpItemKindUnit", { fg = colors.tertiary })
